### ISSUE TITLE
Any one got any idea of how to get full data from device?

### ISSUE THREAD

**Issue by vishnudevk** [lwis/miband-notifier#18]
Anyone got any idea of how to take full activity data from device?

**Comment by chrisvella** [comment]
Have a look at the gadgetbridge open source project. Its more suited to what you are asking about. This project is more about it using the device for notifications rather than a fitness band.

On 6 May 2015 4:57:25 pm AEST, Vishnudev K <notifications@github.com> wrote:
>Anyone got any idea of how to take full activity data from device?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/lwis/miband-notifier/issues/18

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
