### ISSUE TITLE
test on i9505 cm12 

### ISSUE THREAD

**Issue by mat90c** [lwis/miband-notifier#9]
Hi lwis,
I've uploaded your last release on my i9505 cm12, with debug mode I see on setupBluetooth() array pairedDevices not containing miband devices so app can't connect with it. 
I've mifit original app running correctly on background.

I'd like to help you

Thank you

**Comment by lwis** [comment]
This is because Samsung devices don't truly bond with devices - as
described in the readme.

A change would have to be made to store the MAC address of the Bluetooth
devices to connect to - defaulting to that instead of the bonded devices.

I don't have time right now to make this change, but if you create a pull
request I'll be happy to merge.

**Comment by mat90c** [comment]
Thank you, I will try to make this change, I will let you knwo if it works

2015-03-25 17:46 GMT+01:00 Lewis Juggins <notifications@github.com>:

> This is because Samsung devices don't truly bond with devices - as
> described in the readme.
>
> A change would have to be made to store the MAC address of the Bluetooth
> devices to connect to - defaulting to that instead of the bonded devices.
>
> I don't have time right now to make this change, but if you create a pull
> request I'll be happy to merge.
